steps:
  # Install dependencies
  - name: 'node:22'
    entrypoint: npm
    args: ['install']

  # Build the application
  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'bizai-booster',
      '--image', 'gcr.io/$PROJECT_ID/bizai-booster',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'NODE_ENV=production,JWT_SECRET=bizai-boosters-secret-key'
    ]

  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bizai-booster', '.']

  # Push the container to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bizai-booster']

images:
  - 'gcr.io/$PROJECT_ID/bizai-booster'
